services:
    phd_exception_handler:
        class: PhPhD\ExceptionHandler\ExceptionHandlerMiddleware
        arguments:
            - '@phd_exception_handler.bus'

    phd_exception_handler.bus:
        class: Symfony\Component\Messenger\RoutableMessageBus
        arguments:
            - !tagged_locator { tag: 'messenger.bus', index_by: 'id' }

    phd_exception_rethrow_unhandled:
        class: PhPhD\ExceptionHandler\Rethrow\RethrowUnhandledExceptionMiddleware

    phd_exception_chaining:
        class: PhPhD\ExceptionHandler\Chain\ExceptionChainMiddleware

    phd_exception_result_filter:
        class: PhPhD\ExceptionHandler\Result\ExceptionHandlingResultFilterMiddleware
